In [1]:

import numpy as np
import pandas as pd
import plotly.express as px


In [2]:
df=pd.read_csv("univ.csv",header=0)


In [3]:
print(df.head(10))
print(df.__len__())


   World Rank                            Institution         Country  \
0           1                     Harvard University             USA   
1           2  Massachusetts Institute of Technology             USA   
2           3                    Stanford University             USA   
3           4                University of Cambridge  United Kingdom   
4           5                   University of Oxford  United Kingdom   
5           6                   Princeton University             USA   
6           7                    Columbia University             USA   
7           8                  University of Chicago             USA   
8           9             University of Pennsylvania             USA   
9          10                        Yale University             USA   

   National Rank Quality of Education Rank Alumni Employment Rank  \
0              1                         1                      1   
1              2                         4                     12   


In [4]:
df[['Institution','Score']].min()

Institution    A.A. Kharkevich Institute for Information Tran...
Score                                                       65.7
dtype: object

In [5]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [World Rank, Institution, Country, National Rank, Quality of Education Rank, Alumni Employment Rank, Quality of Faculty Rank, Research Performance Rank, Score]
Index: []

In [6]:
#Valori dublicate
df.drop_duplicates()

World Rank                                 Institution         Country  \
0              1                          Harvard University             USA   
1              2       Massachusetts Institute of Technology             USA   
2              3                         Stanford University             USA   
3              4                     University of Cambridge  United Kingdom   
4              5                        University of Oxford  United Kingdom   
...          ...                                         ...             ...   
1995        1996             Santa Catarina State University          Brazil   
1996        1997            Yancheng Institute of Technology           China   
1997        1998  Xi'an University of Science and Technology           China   
1998        1999                    CEU San Pablo University           Spain   
1999        2000                           Huzhou University           China   

      National Rank Quality of Education Rank Alumni Employment Rank  \
0                 1                         1                      1   
1                 2                         4                     12   
2                 3                        10                      4   
3                 1                         3                     25   
4                 2                         7                     27   
...             ...                       ...                    ...   
1995             56                         -                    936   
1996            275                         -                      -   
1997            276                         -                    994   
1998             53                         -                    568   
1999            277                         -                      -   

     Quality of Faculty Rank Research Performance Rank  Score  
0                          1                         1  100.0  
1                          2                         8   96.7  
2                          3                         2   95.1  
3                          4                        10   94.1  
4                          9                         4   93.3  
...                      ...                       ...    ...  
1995                       -                      1938   65.8  
1996                       -                      1920   65.7  
1997                       -                      1937   65.7  
1998                       -                      1992   65.7  
1999                       -                      1922   65.7  

[2000 rows x 9 columns]

In [7]:
#valori nule
df.dropna()

World Rank                                 Institution         Country  \
0              1                          Harvard University             USA   
1              2       Massachusetts Institute of Technology             USA   
2              3                         Stanford University             USA   
3              4                     University of Cambridge  United Kingdom   
4              5                        University of Oxford  United Kingdom   
...          ...                                         ...             ...   
1995        1996             Santa Catarina State University          Brazil   
1996        1997            Yancheng Institute of Technology           China   
1997        1998  Xi'an University of Science and Technology           China   
1998        1999                    CEU San Pablo University           Spain   
1999        2000                           Huzhou University           China   

      National Rank Quality of Education Rank Alumni Employment Rank  \
0                 1                         1                      1   
1                 2                         4                     12   
2                 3                        10                      4   
3                 1                         3                     25   
4                 2                         7                     27   
...             ...                       ...                    ...   
1995             56                         -                    936   
1996            275                         -                      -   
1997            276                         -                    994   
1998             53                         -                    568   
1999            277                         -                      -   

     Quality of Faculty Rank Research Performance Rank  Score  
0                          1                         1  100.0  
1                          2                         8   96.7  
2                          3                         2   95.1  
3                          4                        10   94.1  
4                          9                         4   93.3  
...                      ...                       ...    ...  
1995                       -                      1938   65.8  
1996                       -                      1920   65.7  
1997                       -                      1937   65.7  
1998                       -                      1992   65.7  
1999                       -                      1922   65.7  

[2000 rows x 9 columns]

In [8]:
print(df.__len__())

2000


In [9]:
#numarul de tari din clasament
len(df['Country'].unique())

95

In [10]:
from numpy import corrcoef


corrcoef(df['Score'],df['World Rank'])

array([[ 1.       , -0.9169497],
       [-0.9169497,  1.       ]])

In [11]:
px.scatter(df,'World Rank','Score').update_xaxes(nticks=9)


Strong Reverse correlation between World Rank and Score of the universities 

In [12]:
from numpy import corrcoef
df1=df.copy()
indexAge = df1[ (df1['Quality of Education Rank'] == '-') ].index
df1.drop(indexAge , inplace=True)
corrcoef(df1['Score'],df1['Quality of Education Rank'].astype(int))



array([[ 1.        , -0.35206195],
       [-0.35206195,  1.        ]])

Low Reverse correlation 

In [13]:
df1=df.copy()
indexAge = df1[ (df1['Alumni Employment Rank'] == '-') ].index
df1.drop(indexAge , inplace=True)
corrcoef(df1['Score'],df1['Alumni Employment Rank'].astype(int))


array([[ 1.        , -0.41278661],
       [-0.41278661,  1.        ]])

In [14]:
df1=df.copy()
indexAge = df1[ (df1['Alumni Employment Rank'] == '-') ].index
df1.drop(indexAge , inplace=True)
corrcoef(df1['Score'],df1['Alumni Employment Rank'].astype(int))

array([[ 1.        , -0.41278661],
       [-0.41278661,  1.        ]])

In [15]:
df1=df.copy()
indexAge = df1[ (df1['Research Performance Rank'] == '-') ].index
df1.drop(indexAge , inplace=True)
corrcoef(df1['Research Performance Rank'].astype(int),df1['Score'])


array([[ 1.        , -0.90167376],
       [-0.90167376,  1.        ]])

In [16]:
px.scatter(df1,'Research Performance Rank','Score').update_xaxes(nticks=9)


Very Good reverse corellation between Research Performance Rank and Score

In [17]:
df1=df.copy()
indexAge = df1[ (df1['Quality of Faculty Rank'] == '-') ].index
df1.drop(indexAge , inplace=True)
corrcoef(df1['Quality of Faculty Rank'].astype(int),df1['Score'])

array([[ 1.        , -0.67928058],
       [-0.67928058,  1.        ]])

In [18]:
px.scatter(df1,'Quality of Faculty Rank','Score').update_xaxes(nticks=9)


Goog reverse corellation between Score and Quality of Faculity Rank

In [19]:
counts=df['Country'].value_counts()
counts

USA                347
China              277
Japan              124
United Kingdom      95
France              79
                  ... 
Malawi               1
Kuwait               1
Cameroon             1
Azerbaijan           1
North Macedonia      1
Name: Country, Length: 95, dtype: int64

In [20]:
counts.loc['ROW']=sum(counts<20)

In [21]:
new_df = df.loc[df['Country'].isin(counts.index[counts > 50])]
print(new_df)


      World Rank                                 Institution         Country  \
0              1                          Harvard University             USA   
1              2       Massachusetts Institute of Technology             USA   
2              3                         Stanford University             USA   
3              4                     University of Cambridge  United Kingdom   
4              5                        University of Oxford  United Kingdom   
...          ...                                         ...             ...   
1995        1996             Santa Catarina State University          Brazil   
1996        1997            Yancheng Institute of Technology           China   
1997        1998  Xi'an University of Science and Technology           China   
1998        1999                    CEU San Pablo University           Spain   
1999        2000                           Huzhou University           China   

      National Rank Quality of Educatio

In [22]:
new_df['Country'].value_counts()

USA               347
China             277
Japan             124
United Kingdom     95
France             79
Germany            70
India              68
Italy              66
South Korea        60
Brazil             56
Turkey             55
Spain              53
Name: Country, dtype: int64

In [23]:
print(new_df.__len__())

1350


In [24]:
x=df['Country'].value_counts()/sum(df['Country'].value_counts())*100
#x.loc['ROW']=sum(x.values<1)
x.sort_values(axis=0,ascending=False).head(10)

USA               17.35
China             13.85
Japan              6.20
United Kingdom     4.75
France             3.95
Germany            3.50
India              3.40
Italy              3.30
South Korea        3.00
Brazil             2.80
Name: Country, dtype: float64

In [25]:
import matplotlib.pyplot as plt

In [26]:
from matplotlib.pyplot import ylabel
from pandas import value_counts

px.bar(x[:10]).update_layout(xaxis_title="Country", yaxis_title="Amount Frequency in Top 2000"
)

In [27]:
df1=df.copy()

In [28]:
x=df1[["Country","Score",'Institution']]
x

Country  Score                                 Institution
0                USA  100.0                          Harvard University
1                USA   96.7       Massachusetts Institute of Technology
2                USA   95.1                         Stanford University
3     United Kingdom   94.1                     University of Cambridge
4     United Kingdom   93.3                        University of Oxford
...              ...    ...                                         ...
1995          Brazil   65.8             Santa Catarina State University
1996           China   65.7            Yancheng Institute of Technology
1997           China   65.7  Xi'an University of Science and Technology
1998           Spain   65.7                    CEU San Pablo University
1999           China   65.7                           Huzhou University

[2000 rows x 3 columns]

In [29]:
m=x['Score'].mean()
m

71.58645

In [30]:
date=x.groupby([x["Country"],]).mean()
date

Score
Country             
Algeria    66.200000
Argentina  69.040000
Armenia    71.900000
Australia  73.720513
Austria    71.752941
...              ...
Uruguay    70.600000
Venezuela  66.600000
Vietnam    67.540000
Zambia     67.400000
Zimbabwe   66.700000

[95 rows x 1 columns]

In [31]:

date=date.loc[date['Score'] >= 73]
date['Score'].sort_values(ascending=False)

Country
Switzerland       78.316667
Netherlands       77.446667
Denmark           76.328571
Israel            75.811111
Belgium           75.290909
Singapore         75.175000
Germany           74.471429
Sweden            74.047368
USA               73.917867
Finland           73.890000
Canada            73.816667
Australia         73.720513
United Kingdom    73.625263
Name: Score, dtype: float64

In [32]:
x=df[df['Country']=='Romania']


In [33]:
x=x.loc[:,~df.columns.isin(['Alumni Employment Rank','Quality of Faculty Rank'])]

In [34]:
x

World Rank                                        Institution  Country  \
870          871                            Babeș-Bolyai University  Romania   
890          891                Polytechnic University of Bucharest  Romania   
1009        1010                            University of Bucharest  Romania   
1161        1162                       West University of Timișoara  Romania   
1216        1217   Carol Davila University of Medicine and Pharmacy  Romania   
1451        1452             Alexandru Ioan Cuza University of Iaşi  Romania   
1488        1489  Iuliu Hațieganu University of Medicine and Pha...  Romania   
1638        1639  Grigore T. Popa University of Medicine and Pha...  Romania   
1664        1665                  Transilvania University of Brașov  Romania   
1927        1928  Victor Babeș University of Medicine and Pharma...  Romania   

      National Rank Quality of Education Rank Research Performance Rank  Score  
870               1                         -                       824   71.0  
890               2                         -                       846   70.9  
1009              3                       356                       969   70.2  
1161              4                         -                      1106   69.3  
1216              5                         -                      1152   69.0  
1451              6                         -                      1388   67.9  
1488              7                         -                      1422   67.7  
1638              8                         -                      1564   67.1  
1664              9                         -                      1593   67.0  
1927             10                         -                      1852   66.0

In [35]:
from matplotlib.pyplot import legend


px.bar(x,'Score','Institution',labels='Score',title='Universities in Romania Ranked by Score',color='Score',color_continuous_scale=px.colors.sequential.Blugrn_r)

In [36]:
from matplotlib.pyplot import title, xlabel, ylabel
size1 = [n*100 for n in range(0,len(x["World Rank"]))]
size1.reverse()
fig = px.scatter(x, y="Research Performance Rank", x="World Rank",size=size1,title='Universities in Romania classified by Rank in the World and Research Performance Rank')

fig.show()


In [37]:
#from cProfile import label
#import plotly.graph_objects as go
#fig=go.Figure()
#fig.add_trace(go.Scatter(
#    x=x['World Rank'],
#    y=x['Research Performance Rank']
#)
#)
#fig.update_layout(
#    title="Universities in Romania classified by Rank in the World and Research Performance Rank",
#    xaxis_title="World Rank",
#    yaxis_title="Research Performance Rank",
#    legend_title="Legend Title",
#)

In [38]:
from pandas import DataFrame
new=df.loc[(df['Country']=='Romania') | (df['Country'] == 'Hungary') 
| ((df['Country'] == 'Serbia')| (df['Country'] == 'Austria')| (df['Country'] == 'Ukraine'))]
new.sort_values('Score',ascending=False)

World Rank                                        Institution  Country  \
206          207                               University of Vienna  Austria   
294          295                       Medical University of Vienna  Austria   
347          348                             University of Belgrade   Serbia   
374          375                            University of Innsbruck  Austria   
405          406                    Vienna University of Technology  Austria   
544          545                    Medical University of Innsbruck  Austria   
560          561                         Medical University of Graz  Austria   
562          563                                 University of Graz  Austria   
590          591                           Eötvös Loránd University  Hungary   
677          678                               University of Szeged  Hungary   
682          683                              Semmelweis University  Hungary   
694          695                             University of Debrecen  Hungary   
782          783  University of Natural Resources and Life Scien...  Austria   
827          828                      Graz University of Technology  Austria   
870          871                            Babeș-Bolyai University  Romania   
886          887    Budapest University of Technology and Economics  Hungary   
890          891                Polytechnic University of Bucharest  Romania   
925          926                    Johannes Kepler University Linz  Austria   
1009        1010                            University of Bucharest  Romania   
1069        1070                             University of Salzburg  Austria   
1072        1073        Kharkov Institute of Physics and Technology  Ukraine   
1080        1081                      Paracelsus Medical University  Austria   
1089        1090                                 University of Pécs  Hungary   
1083        1084                             University of Novi Sad   Serbia   
1103        1104          University of Veterinary Medicine, Vienna  Austria   
1111        1112        Institute of Science and Technology Austria  Austria   
1161        1162                       West University of Timișoara  Romania   
1216        1217   Carol Davila University of Medicine and Pharmacy  Romania   
1399        1400       Taras Shevchenko National University of Kyiv  Ukraine   
1451        1452             Alexandru Ioan Cuza University of Iaşi  Romania   
1488        1489  Iuliu Hațieganu University of Medicine and Pha...  Romania   
1516        1517        Vienna University of Economics and Business  Austria   
1579        1580                                  University of Niš   Serbia   
1641        1642                               University of Leoben  Austria   
1638        1639  Grigore T. Popa University of Medicine and Pha...  Romania   
1652        1653                           University of Kragujevac   Serbia   
1664        1665                  Transilvania University of Brașov  Romania   
1668        1669                        Central European University  Hungary   
1677        1678  Institute for Nuclear Research of the National...  Ukraine   
1715        1716  V.M. Glushkov Institute of Cybernetics of the ...  Ukraine   
1735        1736  N.N. Bogolyubov Institute for Theoretical Phys...  Ukraine   
1927        1928  Victor Babeș University of Medicine and Pharma...  Romania   
1948        1949                             University of Pannonia  Hungary   
1965        1966  B. Verkin Institute for Low Temperature Physic...  Ukraine   
1973        1974                            Danube University Krems  Austria   

      National Rank Quality of Education Rank Alumni Employment Rank  \
206               1                       150                    473   
294               2                         -                      -   
347               1                       472                      -   
374               3                  

In [39]:
new1=new[:10].sort_values('Score',ascending=False)
new1


World Rank                      Institution  Country  National Rank  \
206         207             University of Vienna  Austria              1   
294         295     Medical University of Vienna  Austria              2   
347         348           University of Belgrade   Serbia              1   
374         375          University of Innsbruck  Austria              3   
405         406  Vienna University of Technology  Austria              4   
544         545  Medical University of Innsbruck  Austria              5   
560         561       Medical University of Graz  Austria              6   
562         563               University of Graz  Austria              7   
590         591         Eötvös Loránd University  Hungary              1   
677         678             University of Szeged  Hungary              2   

    Quality of Education Rank Alumni Employment Rank Quality of Faculty Rank  \
206                       150                    473                     159   
294                         -                      -                       -   
347                       472                      -                       -   
374                         -                    746                     248   
405                       402                    557                       -   
544                         -                      -                       -   
560                         -                      -                       -   
562                       438                   1202                     161   
590                       259                      -                       -   
677                         -                      -                     197   

    Research Performance Rank  Score  
206                       242   78.5  
294                       246   76.8  
347                       311   76.0  
374                       387   75.6  
405                       389   75.2  
544                       514   73.7  
560                       528   73.5  
562                       690   73.5  
590                       563   73.2  
677                       768   72.5

In [40]:
px.bar(new1,x='Score',y='Institution',title='Universities with the highest score of Romania and their neighboring countries ',)

In [41]:
ax=new[['Country','Score']].groupby('Country').mean().sort_values('Score',ascending=False)
ax

Score
Country           
Austria  71.752941
Hungary  70.487500
Serbia   70.000000
Romania  68.610000
Ukraine  67.366667

In [42]:
px.bar(ax,x='Score',color='Score',color_continuous_scale=px.colors.sequential.RdBu,title="Romanian's score comparing to their neighboring countries")